import {API_PARAMS, API_PATH, BASE_URL, PROXY_URL} from './api';
import {MAX_API_VACANCIES, VACANCIES_COUNT_ON_PAGE} from './constants';
import {DESIGN_EXAMPLE_WINDOW_HEIGHT, HEADER_HEIGHT} from './styles';

export {
  API_PARAMS,
  API_PATH,
  BASE_URL,
  DESIGN_EXAMPLE_WINDOW_HEIGHT,
  HEADER_HEIGHT,
  MAX_API_VACANCIES,
  PROXY_URL,
  VACANCIES_COUNT_ON_PAGE,
};
