import {API_PATH, BASE_DATA_API, BASE_URL, PROXY_URL} from './api';
import {DESIGN_EXAMPLE_WINDOW_HEIGHT, HEADER_HEIGHT} from './styles';

export {API_PATH, BASE_DATA_API, BASE_URL, DESIGN_EXAMPLE_WINDOW_HEIGHT, HEADER_HEIGHT, PROXY_URL};
